{{- if eq .Values.database.type "internal" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fichador.fullname" . }}-db
  labels:
    {{- include "fichador.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    {{- include "fichador.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
{{- end }}