{{- if .Values.gatewayApi.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "fichador.fullname" . }}
  labels:
    {{- include "fichador.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.gatewayApi.gatewayName }}
      namespace: {{ .Values.gatewayApi.namespace }}
  hostnames:
    - {{ .Values.gatewayApi.hostname | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "fichador.fullname" . }}
          port: {{ .Values.service.port }}
{{- end }}