apiVersion: v2
name: fichador
description: Helm chart para Fichador App con soporte Dual DB y Gateway API
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: 15.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled